pipeline {
    agent any
    options {
        skipDefaultCheckout()
    }
    stages {
        stage('Prepare build folder') {
            steps {
                cleanWs()
            }
        }

        stage('Get source code') {
            steps {
                checkout scm
            }
        }

        stage('Build Python implementation') {
            steps {
                dir('./Python/pyinstaller') {
                    sh '/home/matt/.venvs/CXR_env/bin/pyinstaller --distpath=../ folder.spec'
                }
            }
        }

        stage('Build C++ implementation') {
            steps {
                sh 'mkdir ./Cpp/build'
                dir('./Cpp/build') {
                    sh '/usr/lib/qt5/bin/qmake /home/matt/Documents/CXR_View_Classification/Cpp/CXR_classify/CXR_classify.pro -spec linux-g++ CONFIG+=debug'
                    sh '/usr/bin/make -j10'
                }
            }
        }

        stage('Build shared libraries') {
            steps {
                sh 'mkdir ./Combined/DesktopApp/build'
                dir('./Combined/DesktopApp/build') {
                    sh 'cmake ../src'
                    sh 'cmake --build .'
                }
            }
        }

        stage('Copy repository to VM shared folder') {
            steps {
                /*
                jenkins user can't write to shared folder in Matt so we must allow
                jenkins to write to folder. I used:
                sudo chmod -R a+rw /home/matt/SharedFolder_host
                before and after the call below. Before to write and after so the VM
                can execute and operate on the files. However I did this from host terminal
                so I need to find a way to do it using Jenkinsfile. 
                */
                sh 'cp -r . /home/matt/SharedFolder_Host'
            }
        }
    }
}