name: test_env3
channels:
  - defaults
  - conda-forge
dependencies:
  - nomkl
  - python=3.7
  - psycopg2=2.8.4
  - pylint=2.4.4
  - requests=2.22.0
  - numpy=1.18.1
  - matplotlib=3.1.3
  - scipy=1.4.1
  - scikit-image=0.16.2
  - scikit-learn=0.22.1
  - pyqt=5.9.2
  - pydicom=1.4.1
  - nibabel=3.0.1
  - opencv=3.4.2
  - pip=20.0.2

  # Make sure nomkl is there, then create environment, then add pyinstaller with:
  # pip install https://github.com/pyinstaller/pyinstaller/tarball/develop