name: test
channels:
  - defaults
  - conda-forge
dependencies:
  - nomkl
  - python=3.7
  - psycopg2=2.8.4
  - pylint=2.4.4
  - requests=2.22.0
  - gunicorn=20.0.4
  - numpy=1.18.1
  - matplotlib=3.1.3
  - scipy=1.4.1
  - scikit-image=0.16.2
  - scikit-learn=0.22.1
  - pydicom=1.4.1
  - nibabel=3.0.1
  - opencv=3.4.2
  - flask=1.1.1
  - pip=20.0.2
  - pip:
    - PyQt5
    - https://github.com/pyinstaller/pyinstaller/tarball/develop
    - shared-image-processing==0.0.2
    - metadata-to-db==0.0.1
    - ../Python/SharedCode/